### PR TITLE
Update CID to v1.5.1

### PR DESCRIPTION
**Pull request by cyberpower678**
Support the semicolon being used as a separator for query strings.

### CODE REVIEW

**Comment by cyberpower678** [comment]
Unfortunately I have many false positives with this issue.  The semicolon is getting encoded.  While the specifications say what they say, the fact of the matter is there are Webservers using this unused reserved character.

**Comment by kaldari** [comment]
@cyberpower678: Since semicolons are a reserved character in URIs it probably makes sense to not encode them in most cases (as you are changing). What doesn't make sense is using semicolons to designate the beginning of the query string. Is that part really needed to address the false positives?

**Comment by cyberpower678** [comment]
The way I see it, reserved characters should be encoded unless the are used accordingly.  AFAIK, semicolons have no place in the path. So if an actual query string exists and a semicolon, the semicolon will be encoded to conform to URL standards.  However, since a lot of Webservers, for some reason, are using them to mark the start of a query string and to separate foo=bar values, this approach takes that into consideration while still enforcing URI standards in other cases.  So to in short, simply not encoding them is not the way to go, but also ignoring how they are being used isn't either.

**Comment by kaldari** [comment]
I think the basic problem is that it's impossible for us to "fix" bad URLs without introducing false positives. We're going to have to keep creating more and more complicated exceptions to deal with wonky web servers that handle URLs in unexpected ways. Rather than continuing to make the code more complicated in our whack-a-mole approach, I think it might be better for us to let bad URLs simply fail the check. What if we removed all the encoding and decoding code (with it's complicated exceptions) and just accepted the URLs at face value? This might result in some URLs being marked as dead when the pages still exist, but it would be the fault of bad URLs that could be fixed, not our fault. Trying to guess how web servers really want to receive URLs seems like an impossible task. Every time we fix an issue for one web server we are likely creating new false positives on others.

**Comment by cyberpower678** [comment]
We haven't introduced false positives.  I'm not creating an exception for every little problem, just the ones more commonly used.  This is one of them.  And removing the sanitizer will break IABot entirely.  That routine is heavily depended on as well as introduces a whole lot more new false positives.  The last time the bot simply accepted URLs at face values, decoded characters in the URLs that web browsers encode internally failed to curl because it was an invalid URL.  Curl needs legal URLs to work with.

**Comment by cyberpower678** [comment]
Plus when we go to UTF-8 URLs like Russian or Chinese sites, those will make Curl throw up at last check.

**Comment by kaldari** [comment]
Fair enough. Regardless, even if the web server is treating the data after the semicolon like a query string, by definition it isn't a query string (per https://tools.ietf.org/html/rfc3986#section-3.4), and it's still part of the path. Many REST API servers also do a similar thing, but with slashes instead of semicolons. For example, https://ores.wikimedia.org/v3/scores/wikidatawiki/421063984/damaging (which would actually make more sense as https://ores.wikimedia.org?verion=v3&data=scores&wiki=wikidatawiki&revision=421063984&model=damaging). In this case the server is treating the slashes as query parameter delimiters rather than directory markers (which is totally fine for them to do). I think the right solution here is to just not encode semicolons in the URL. We know that curl isn't going to care, and I can't think of any situations where this would cause a problem. Can you?

**Comment by cyberpower678** [comment]
So with the taste case I added, the ; separates the path with the query.  Why? because it uses "query=" in the URL.  = Have no place in the path in the unencoded state, IIRC.  But they are perfectly legal in the query string.  That's why I have it processing it as a query.

**Comment by cyberpower678** [comment]
http://parlinfo.aph.gov.au/parlInfo/search/display/display.w3p;query=Id%3A%22handbook%2Fnewhandbook%2F2014-10-31%2F0049%22 is the test case.

**Comment by cyberpower678** [comment]
I stand corrected with https://www.google.se/maps/@60.0254617,14.9787602,3a,75y,133.6h,84.1t/data=!3m6!1e1!3m4!1sqMn_R4TRF0CerotZfLlg8g!2e0!7i13312!8i6656

**Comment by cyberpower678** [comment]
I will make the appropriate modifications.

**Comment by cyberpower678** [comment]
I've made the modifications.  Semicolons are now entirely unencoded.

**Pull request merged**
