### PR TITLE
Test

### PR DESCRIPTION
**Pull request by cyberpower678**
Add error pass back for true results.

### CODE REVIEW

**Comment by cyberpower678** [comment]
Travis appears broken.

**Comment by cyberpower678** [comment]
I would highly recommend squashing and merging, rather than just merging.

**Comment by Niharika29** [comment]
I would really really not like to have this merged. It makes the code very incomprehensible and doesn't add any real benefit. 
If we want to do this, it'd have to be implemented better. Combining with the return value in an array, maybe, maybe not.
@kaldari I'd like to hear your opinion.

**Comment by Niharika29** [comment]
By the way, Travis is complaining about legit problems: https://travis-ci.org/wikimedia/DeadlinkChecker/jobs/178948709#L321

**Comment by cyberpower678** [comment]
So why combine it in the return value, and force rewrite all of the tests?  I simply added an optional variable that can be passed to the class.  It doesn't break any existing installations, and it adds the ability to see what the error was that resulted in a dead response, be it a 404, curl error, or root redirect.  This would be used for FP reporting especially when running the algorithm on labs to see why it fails there, but works on my computer.  I'm not inclined to emulate a full Firefox request in a bash command, that's ridiculously tedious.

**Comment by cyberpower678** [comment]
So per Niharika, the constant passing of &$errors, was replaced with a protected variable in the class, and retrieving it through the getErrors() function

**Comment by cyberpower678** [comment]
I still recommend squashing this before merging this, if it gets approved.

**Comment by kaldari** [comment]
Looks good to me. Agree that the getErrors() approach is better.

**Pull request merged**
