### PR TITLE
Update CID to v1.2

### PR DESCRIPTION
**Pull request by cyberpower678**
Allow for the stripping of fragments in the sanitizer.

### CODE REVIEW

**Comment by cyberpower678** [comment]
I made a modification to the encoding process.  It now encodes spaces in queries into %20 instead of + because more servers, if not all, support %20 while not supporting +.

**Comment by Niharika29** [comment]
I'd like to see some more comments on what exactly this PR is for and why we need it.

**Comment by cyberpower678** [comment]
So this pull requests make the following additions and changes.

Firstly, a boolean can be passed instructing the sanitizer to leave out the fragment.  This is useful for sites that don't like a fragment being passed.  It's always recommended to drop the fragment, but the default is not to for backwards compatibility.  For software reliant on sanitized URLs, removing the fragment is of no consequence when CURLing the URL.

Secondly, statistics show that servers are more likely to support %20 in the query instead of the + for whitespace.  Adjust the sanitizer to encode whitespace as %20 instead.

Lastly, fixed a bug where URLs with a %23 in it code be mistaken as the start of a fragment and encoding the URL as such, which will also lead to too much URL being removed if the sanitizer drops the fragment.

**Comment by Niharika29** [comment]
> Secondly, statistics show that servers are more likely to support %20 in the query instead of the + for whitespace. Adjust the sanitizer to encode whitespace as %20 instead.

Where's this happening in the PR?

**Comment by cyberpower678** [comment]
urlencode has been changed to rawurlencode.

**Comment by Niharika29** [comment]
Merged.

**Pull request merged**
